### ISSUE TITLE
Trying to get property of non object (null)

### ISSUE THREAD

**Issue by jrean** [karlmonson/laravel-ping#1]
Hi,

If the request timeout the following Exception is caught in your method `check()`:

```
		} catch(ConnectException $e) {
			$response = $e->getResponse();
            dd($e->getResponse());
			$this->responseCode = $response->getStatusCode();
		}
```

`getResponse()` is not accessible...

:-)

**Comment by karlmonson** [comment]
Thank you for the heads up... I will look into this.

**Comment by DavidLambauer** [comment]
+1. The ConnectException overwrites the method getStatusCode and return null. I would appreciate a fix.

**Comment by karlmonson** [comment]
This has been resolved. Run composer update to get the latest version with the fix.
