### ISSUE TITLE
Redirect URI, html/index.html, does not use one of the allowed redirect protocols: http, https 

### ISSUE THREAD

**Issue by aijcoa** [karlmonson/laravel-ping#2]
I'm looping over some IPs from records in my DB, and after the 3rd record I get this error.

`Redirect URI, html/index.html, does not use one of the allowed redirect protocols: http, https`.

It works fine in local env, but not on prod with HTTPS. 

any ideas?

my code:

    foreach ($sim_ips as $ip) {
      if (($ip != "") && ($ip != "FAIL")) {
      	$health = Ping::check($ip);

        $sim = Sim::where('ip', $ip)->first();

        if($health == 200) {
      		$sim->status = 'online';
      	} else {
      		$sim->status = 'offline';
      	}

        $sim->save();
      }
    }

**Comment by karlmonson** [comment]
Hmm I've never seen this error before. What is the output of `$health` when you get this error?

**Comment by jmanoel** [comment]
This happens because the frameworks try to access the application on http or https ports even just ping. Something similar occurs if you try to "ping" and url that has auto signed ssl certificate.
