### ISSUE TITLE
Can it support Larave 8?

### ISSUE THREAD

**Issue by CODEbyPoHsiang** [karlmonson/laravel-ping#5]
Hello author,
Can you update the package and support Laravel 8?
Thank you

**Comment by mayeenulislam** [comment]
## Alternative 1 (tested)
I resolved it locally for now - using the code in **Laravel 8.x with PHP 7.3+**. Using the code of the package locally. You will only need the `Ping.php` class.

1. Place the file somewhere in your App/Controller directory
2. Change the namespace
3. Install guzzle yourself `composer require guzzlehttp/guzzle`
4. Replace `use Ping` with `use App\Http\Controllers\Ping;` (your path)
5. Replace `Ping::check` with `(new Ping)->check`

You are done.

> **NOTE:** You won't get any update of the package if anything happens in future

## Alternative 2 (not tested)
You can clone the repository in your project like:

1. `git clone git@github.com:karlmonson/laravel-ping.git packages/karlmonson/laravel-ping/ && cd packages/karlmonson/laravel-ping/ && rm -rf .git`
2. Open the package's `composer.json` (located in `packages/karlmonson/laravel-ping/composer.json`) and in [line#19](https://github.com/karlmonson/laravel-ping/blob/1.0.7/composer.json#L19) add Laravel 8
```
"illuminate/support": "^5.1 || ^5.7 || ^5.8 || ^6.0 || ^7.0 || ^8.0",
```
3. Add the package to composer JSON:
```json
"autoload": {
    "psr-4": {
        "Karlmonson\\Ping\\": "packages/technovistalimited/karlmonson/laravel-ping/src"
    }
}
```
4. run `composer dump-autoload`
5. then follow all the Installation steps as mentioned [in the Readme](https://github.com/karlmonson/laravel-ping/tree/1.0.7) as use it as is

**Comment by ankitabhatti05** [comment]
@mayeenulislam Your alternative 1 is working for me thanks!
